name: Update Hit Counter

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-hits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Process visits and update counter
        run: |
          # Get current count
          current_total=$(jq '.total' data/hits.json)
          current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Update hits.json
          jq --arg date "$current_date" \
             --arg total "$(($current_total + 1))" \
             '.total = ($total | tonumber) | .last_updated = $date' \
             data/hits.json > data/hits.json.tmp && mv data/hits.json.tmp data/hits.json
          
          # Configure git
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # Commit and push if there are changes
          git add data/hits.json
          git diff --staged --quiet || (git commit -m "Update hit counter" && git push)